-- Database migration script for Port Sudan Ahlia University
-- Updates the schema to auto-generate department and receipt IDs

-- Create sequences for auto-generated IDs
CREATE SEQUENCE SRRA.DEPARTMENT_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SRRA.RECEIPT_ID_SEQ START WITH 1 INCREMENT BY 1;

-- 1. Create temporary tables to hold the existing data
CREATE TABLE SRRA.DEPARTMENT_TEMP AS SELECT * FROM SRRA.DEPARTMENT;
CREATE TABLE SRRA.RECEIPT_TEMP AS SELECT * FROM SRRA.RECEIPT;

-- 2. Drop the existing tables and constraints that need to be modified
ALTER TABLE SRRA.STUDENT DROP CONSTRAINT FK_DEPARTMENT;
ALTER TABLE SRRA.RECEIPT DROP CONSTRAINT FK_STUDENT;
ALTER TABLE SRRA.RECEIPT DROP CONSTRAINT FK_ENTERED_BY;
DROP TABLE SRRA.RECEIPT;
DROP TABLE SRRA.DEPARTMENT;

-- 3. Re-create the department table with auto-generated ID
CREATE TABLE SRRA.DEPARTMENT (
  DEPARTMENT_ID VARCHAR2(15) DEFAULT 'D' || TO_CHAR(SRRA.DEPARTMENT_ID_SEQ.NEXTVAL, 'FM000000') PRIMARY KEY NOT NULL,
  DEPARTMENT_NAME VARCHAR2(150) NOT NULL,
  SEMESTERS_NO NUMBER(2) NOT NULL
);

-- 4. Re-create the receipt table with auto-generated ID
CREATE TABLE SRRA.RECEIPT (
  RECEIPT_ID VARCHAR2(15) DEFAULT 'R' || TO_CHAR(SRRA.RECEIPT_ID_SEQ.NEXTVAL, 'FM000000') PRIMARY KEY NOT NULL,
  STUDENT_ID VARCHAR2(15) NOT NULL,
  BANK_RECEIPT_NO VARCHAR2(50),
  ENTERED_BY VARCHAR2(15) NOT NULL,
  ENTRY_DATE DATE DEFAULT SYSDATE NOT NULL,
  AMOUNT_NUMBER NUMBER(10, 2) NOT NULL,
  AMOUNT_LETTERS VARCHAR2(200) NOT NULL,
  PAID_ITEMS VARCHAR2(3) NOT NULL,
  SEMESTER_NO NUMBER(2) NOT NULL,
  COMMENTS VARCHAR2(250)
);

-- 5. Restore the data from the temporary tables
INSERT INTO SRRA.DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, SEMESTERS_NO)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, SEMESTERS_NO FROM SRRA.DEPARTMENT_TEMP;

INSERT INTO SRRA.RECEIPT (RECEIPT_ID, STUDENT_ID, BANK_RECEIPT_NO, ENTERED_BY, ENTRY_DATE, AMOUNT_NUMBER, AMOUNT_LETTERS, PAID_ITEMS, SEMESTER_NO, COMMENTS)
SELECT RECEIPT_ID, STUDENT_ID, BANK_RECEIPT_NO, ENTERED_BY, ENTRY_DATE, AMOUNT_NUMBER, AMOUNT_LETTERS, PAID_ITEMS, SEMESTER_NO, COMMENTS FROM SRRA.RECEIPT_TEMP;

-- 6. Drop the temporary tables
DROP TABLE SRRA.DEPARTMENT_TEMP;
DROP TABLE SRRA.RECEIPT_TEMP;

-- 7. Add constraints back
ALTER TABLE SRRA.STUDENT
 ADD CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES SRRA.DEPARTMENT (DEPARTMENT_ID);

ALTER TABLE SRRA.RECEIPT
 ADD CONSTRAINT FK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES SRRA.STUDENT (STUDENT_ID);

ALTER TABLE SRRA.RECEIPT
 ADD CONSTRAINT FK_ENTERED_BY FOREIGN KEY (ENTERED_BY) REFERENCES SRRA.USERS (USER_ID);

-- 8. Update sequences based on the existing data
-- This ensures that new auto-generated IDs won't conflict with existing ones
DECLARE
  l_max_dept_id NUMBER;
  l_max_receipt_id NUMBER;
BEGIN
  -- Find the current maximum numerical part of department IDs
  SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(DEPARTMENT_ID, '[0-9]+'))), 0)
  INTO l_max_dept_id
  FROM SRRA.DEPARTMENT;
  
  -- Find the current maximum numerical part of receipt IDs
  SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(RECEIPT_ID, '[0-9]+'))), 0)
  INTO l_max_receipt_id
  FROM SRRA.RECEIPT;
  
  -- Set the sequence next values to be greater than the current max values
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SRRA.DEPARTMENT_ID_SEQ INCREMENT BY ' || (l_max_dept_id + 1 - SRRA.DEPARTMENT_ID_SEQ.NEXTVAL);
  EXECUTE IMMEDIATE 'SELECT SRRA.DEPARTMENT_ID_SEQ.NEXTVAL FROM DUAL';
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SRRA.DEPARTMENT_ID_SEQ INCREMENT BY 1';
  
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SRRA.RECEIPT_ID_SEQ INCREMENT BY ' || (l_max_receipt_id + 1 - SRRA.RECEIPT_ID_SEQ.NEXTVAL);
  EXECUTE IMMEDIATE 'SELECT SRRA.RECEIPT_ID_SEQ.NEXTVAL FROM DUAL';
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SRRA.RECEIPT_ID_SEQ INCREMENT BY 1';
END;
/

-- 9. Add indexes and unique constraints
CREATE INDEX IDX_STUDENT_ID ON SRRA.RECEIPT (STUDENT_ID);
ALTER TABLE SRRA.DEPARTMENT ADD CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (DEPARTMENT_NAME);

-- Commit changes
COMMIT; 