-- Database schema setup script for Port Sudan Ahlia University
-- Student Registration Receipts Archive System

-- Create SRRA schema if it doesn't exist
CREATE USER SRRA IDENTIFIED BY ORCL
QUOTA UNLIMITED ON USERS
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE TO SRRA;
GRANT EXP_FULL_DATABASE TO SRRA;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO SRRA;

-- Create sequences for auto-generated IDs
CREATE SEQUENCE SRRA.DEPARTMENT_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SRRA.RECEIPT_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create department table with auto-generated ID
CREATE TABLE SRRA.DEPARTMENT (
  DEPARTMENT_ID VARCHAR2(15) NOT NULL PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(150) NOT NULL,
  SEMESTERS_NO NUMBER(2) NOT NULL
);

-- Create student table with manually entered ID
CREATE TABLE SRRA.STUDENT (
  STUDENT_ID VARCHAR2(15) PRIMARY KEY NOT NULL, -- Manually entered
  FULL_NAME VARCHAR2(150) NOT NULL,
  SEMESTER_NO NUMBER(2),
  DEPARTMENT_ID VARCHAR2(15),
  REGISTRATION_STATUS VARCHAR2(1)
);

-- Create users table with manually entered ID
CREATE TABLE SRRA.USERS (
  USER_ID VARCHAR2(15) PRIMARY KEY NOT NULL, -- Manually entered
  USER_NAME VARCHAR2(200) NOT NULL,
  HASHED_PASSWORD VARCHAR2(200) NOT NULL,
  ROLE VARCHAR2(5) NOT NULL
);

-- Create receipt table with auto-generated ID
CREATE TABLE SRRA.RECEIPT (
  RECEIPT_ID VARCHAR2(15) NOT NULL PRIMARY KEY,
  STUDENT_ID VARCHAR2(15) NOT NULL,
  BANK_RECEIPT_NO VARCHAR2(50),
  ENTERED_BY VARCHAR2(15) NOT NULL,
  ENTRY_DATE DATE DEFAULT SYSDATE NOT NULL,
  AMOUNT_NUMBER NUMBER(10, 2) NOT NULL,
  AMOUNT_LETTERS VARCHAR2(200) NOT NULL,
  PAID_ITEMS VARCHAR2(3) NOT NULL,
  SEMESTER_NO NUMBER(2) NOT NULL,
  COMMENTS VARCHAR2(250)
);

-- Add constraints
ALTER TABLE SRRA.STUDENT
 ADD CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES SRRA.DEPARTMENT (DEPARTMENT_ID);

ALTER TABLE SRRA.STUDENT
 ADD CONSTRAINT CHK_SEMESTER_NO_STUDENT CHECK (SEMESTER_NO > 0);

ALTER TABLE SRRA.RECEIPT
 ADD CONSTRAINT FK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES SRRA.STUDENT (STUDENT_ID);

ALTER TABLE SRRA.RECEIPT
 ADD CONSTRAINT FK_ENTERED_BY FOREIGN KEY (ENTERED_BY) REFERENCES SRRA.USERS (USER_ID);

ALTER TABLE SRRA.RECEIPT
 ADD CONSTRAINT CHK_SEMESTER_NO CHECK (SEMESTER_NO > 0);

-- Add indexes
CREATE INDEX IDX_STUDENT_ID ON SRRA.RECEIPT (STUDENT_ID);
CREATE INDEX IDX_USER_NAME ON SRRA.USERS (USER_NAME);
CREATE INDEX IDX_STUDENT_NAME ON SRRA.STUDENT (FULL_NAME);
CREATE INDEX IDX_DEPARTMENT_NAME ON SRRA.DEPARTMENT (DEPARTMENT_NAME);

-- Add unique constraints
ALTER TABLE SRRA.USERS ADD CONSTRAINT UQ_USER_NAME UNIQUE (USER_NAME);
ALTER TABLE SRRA.DEPARTMENT ADD CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (DEPARTMENT_NAME);

-- Commit changes
COMMIT; 