SELECT RECEIPT_ID, BANK_RECEIPT_NO, ENTRY_DATE, AMOUNT_NUMBER,
       AMOUNT_LETTERS, PAID_ITEMS, SEMESTER_NO, COMMENTS,
       STUDENT_ID, STUDENT_NAME,
       DEPARTMENT_ID, DEPARTMENT_NAME,
       ENTERED_BY_NAME
FROM (
    SELECT r.RECEIPT_ID, r.BANK_RECEIPT_NO, r.ENTRY_DATE, r.AMOUNT_NUMBER,
           r.AMOUNT_LETTERS, r.PAID_ITEMS, r.SEMESTER_NO, r.COMMENTS,
           s.STUDENT_ID, s.FULL_NAME AS STUDENT_NAME,
           d.DEPARTMENT_ID, d.DEPARTMENT_NAME,
           u.USER_NAME AS ENTERED_BY_NAME,
           ROWNUM AS rn
    FROM SRRA.RECEIPT r
    JOIN SRRA.STUDENT s ON r.STUDENT_ID = s.STUDENT_ID
    JOIN SRRA.DEPARTMENT d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
    JOIN SRRA.USERS u ON r.ENTERED_BY = u.USER_ID
    ORDER BY r.ENTRY_DATE DESC
)
WHERE rn > :0 AND rn <= :0 + :20;

//Navigate to the following registry path: HKEY_LOCAL_MACHINE\SOFTWARE\ORACLE\HOMExx, where "xx" represents the Oracle Home number.

